### ISSUE TITLE
Install aiidalab-app dependencies during testing

### ISSUE THREAD

**Issue by danielhollas** [csadorf/aiidalab-test-app-action#15]
Looking at `index.js` in this repo, it seems that the app dependencies are not installed (while they are installed automatically via pip if the app is installed via `aiidalab install app`). Looks like the repo with the app is mounted to the aiidalab container, but dependencies are not installed. I wonder why that is? I get that this speeds up the CI runs, but isn't it a problem in a general case? Currently I can workaround this for my case, but I wonder how come this is not a problem for example for `aiidalab-qe` app.

Perhaps there could be an additional option to install dependencies? (or an option to specify the list of dependencies explicitly, to avoid installing dependencies that are not needed for tests).

**Comment by csadorf** [comment]
@danielhollas Thank you for reporting this. This action is currently not well-maintained and is due for an overhaul. I've put this on the roadmap. I believe that the installation mechanism did not exist yet, when I first implement the action.
